import "./_group.css";
import { useMemo, useState } from "react";

type AnyRecord = Record<string, any>;
type Template = AnyRecord & { id: string; definition: AnyRecord };
type Run = AnyRecord & { id: string; status: string };
const templates: Template[] = [{
  id:"docs",name:"Documentation lifecycle patrol",kind:"docs_sync",summary:"Keep repository documentation aligned with implementation changes.",capabilityTags:["read-repo","human-gated"],
  definition:{name:"docs-lifecycle-patrol",goal:"Review documentation drift and propose safe, evidence-backed updates.",mode:"human-gated",steps:[
    {title:"Inspect repository context",purpose:"Read the configured documentation and source paths.",allowedPaths:["README.md","src","tests"]},
    {title:"Compare implementation",purpose:"Identify stale examples, commands, and behavioral claims.",allowedPaths:["README.md"]},
    {title:"Prepare evidence",purpose:"Summarize proposed changes for human approval.",allowedPaths:[]}
  ],budget:{maxDurationMinutes:30,maxToolCalls:200},safety:{allowedPaths:["README.md"],protectedBranches:["main"],forbiddenActions:["Never commit directly to protected branches"]},escalationRules:["Escalate ambiguous behavior to an operator"],decisionRules:[{signal:"documentation drift",action:"Prepare a human-reviewed patch"},{signal:"unsafe repository state",action:"Stop and escalate"}]}
},{
  id:"audit",name:"Repository safety audit",kind:"repo_audit",summary:"Inspect a repository against its declared safety boundaries.",capabilityTags:["policy","evidence"],
  definition:{name:"repository-safety-audit",goal:"Check repository configuration and report boundary violations.",mode:"human-gated",steps:[{title:"Read policy",purpose:"Load project rules and protected paths.",allowedPaths:["README.md"]},{title:"Audit boundaries",purpose:"Compare intended operations with repository state.",allowedPaths:[]}],budget:{maxDurationMinutes:20,maxToolCalls:120},safety:{allowedPaths:[],protectedBranches:["main"],forbiddenActions:["No writes during audit"]},escalationRules:["Escalate any policy violation"],decisionRules:[{signal:"violation found",action:"Stop and notify operator"}]}
}];
const initialRuns: Run[]=[{id:"run-1042",status:"passed",projectName:"looptask",loopName:"docs-lifecycle-patrol",agentCellId:"looptask/docs-lifecycle-patrol/default"}];

export function Current() {
  const [selected,setSelected]=useState<Template>(templates[0]); const [runs,setRuns]=useState(initialRuns); const [events,setEvents]=useState<AnyRecord[]>([]);
  const [project,setProject]=useState("looptask"),[repository,setRepository]=useState(""),[branch,setBranch]=useState("main"),[stack,setStack]=useState("rust"),[docs,setDocs]=useState("README.md"),[source,setSource]=useState("src,tests"),[celld,setCelld]=useState("http://127.0.0.1:9876"),[loopName,setLoopName]=useState(selected.definition.name),[agentKey,setAgentKey]=useState("default"),[goal,setGoal]=useState(selected.definition.goal),[activeView,setActiveView]=useState("workspace"),[status,setStatus]=useState("待命"),[notice,setNotice]=useState("未开始运行"),[toast,setToast]=useState("");
  const definition=selected.definition;
  const update=(setter:(v:string)=>void)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setter(e.target.value);
  const projectConfig=useMemo(()=>({name:project,repository:repository||null,defaultBranch:branch,techStack:splitList(stack),docs:splitList(docs),sourcePaths:splitList(source),celld:{publicUrl:celld},loops:[{...definition,name:loopName,goal:goal||definition.goal}],}),[project,repository,branch,stack,docs,source,celld,definition,loopName,goal]);
  function choose(t:Template){setSelected(t);setLoopName(t.definition.name);setGoal(t.definition.goal);}
  function notify(message:string){setNotice(message);setToast(message);window.setTimeout(()=>setToast(""),4200)}
  function action(kind:string){if(kind==="dispatch"){setStatus("运行中");setRuns([{...initialRuns[0],id:`run-${Date.now()}`,status:"running"},...runs]);setEvents([{id:"event-1",eventType:"run.started",payloadJson:{agentCellId:`${project}/${loopName}/${agentKey}`}}]);notify("Loop 已进入 Agent cell。")}else notify(kind==="save"?"项目配置已安全保存。":kind==="validate"?"完整策略通过，可以预览或派发。":"执行计划已生成。")}
  const user={displayName:"Operator",email:"operator@looptask.local"};
  return <div className="app min-h-screen"><aside className="sidebar"><Brand kicker="Control plane"/><div className="side-kicker">Workspace</div><nav className="nav" aria-label="主导航">{[["workspace","▣","Loop workspace"],["runs","⚑","运行记录"],["policies","◇","安全策略"]].map(([view,icon,label])=><button className={activeView===view?"active":""} key={view} onClick={()=>{setActiveView(view);if(view!=="workspace")notify("这个视图会在 Loop 运行后承载对应记录。")}} type="button"><span className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-spacer"/><div className="user-chip"><div className="avatar">O</div><div className="user-copy"><strong>{user.displayName}</strong><span>{user.email}</span></div><button className="logout" onClick={()=>notify("预览模式：已安全退出。")} title="退出登录" type="button">↗</button></div></aside>
  <main className="main"><header className="topbar"><div><div className="breadcrumb">Operations · {activeView==="workspace"?"Loop workspace":activeView}</div><div className="top-title">Engineering control center</div></div><div className="health"><i className="dot live"/>服务在线</div></header><section className="page-intro"><div><div className="eyebrow">Core operation</div><h1>Loop workspace</h1></div><span className="save-state">{notice}</span></section><div className="page-toolbar"><span>选择能力模板后，检查策略边界，再生成或派发执行计划。</span><button className="secondary" onClick={()=>notify("模板已刷新。")} type="button">刷新模板</button></div>
  <div className="workspace"><section className="panel"><PanelHead title="01 · 连接项目" label="CONTEXT"/><div className="panel-body"><div className="repo-preview"><div className="repo-icon">⌘</div><div className="repo-copy"><strong>{repository?project:"尚未关联仓库"}</strong><span>{repository||"输入仓库地址后开始"}</span></div></div><Field label="GitHub repository URL"><input type="url" value={repository} onChange={update(setRepository)} placeholder="https://github.com/owner/repository"/></Field><div className="grid-2"><Field label="项目名称"><input value={project} onChange={update(setProject)}/></Field><Field label="默认分支"><input className="mono" value={branch} onChange={update(setBranch)}/></Field></div><details className="advanced"><summary>高级上下文设置</summary><div className="grid-2"><Field label="文档路径"><input className="mono" value={docs} onChange={update(setDocs)}/></Field><Field label="源码路径"><input className="mono" value={source} onChange={update(setSource)}/></Field></div><Field label="技术栈"><input className="mono" value={stack} onChange={update(setStack)}/></Field><Field label="celld URL"><input className="mono" value={celld} onChange={update(setCelld)}/></Field></details></div></section>
  <section className="panel"><PanelHead title="02 · 选择 Loop 能力" label="CAPABILITY"/><div className="panel-body"><div className="template-list">{templates.map(t=><button className={`template ${selected.id===t.id?"selected":""}`} key={t.id} onClick={()=>choose(t)} type="button"><div className="template-top"><span className="template-title">{t.name}</span><span className="template-badge">{t.kind}</span></div><div className="template-summary">{t.summary}</div><div className="tags">{t.capabilityTags.map((tag:string)=><span key={tag}>{tag}</span>)}</div></button>)}</div></div></section>
  <section className="panel wide"><PanelHead title="03 · Loop 执行台" label="EXECUTION"/><div className="panel-body"><div className="definition-head"><div><div className="definition-name">{definition.name}</div><div className="definition-goal">{selected.summary||definition.goal}</div></div><span className="mode">{definition.mode}</span></div><div className="grid-2"><Field label="Loop 名称"><input value={loopName} onChange={update(setLoopName)}/></Field><Field label="Agent key"><input className="mono" value={agentKey} onChange={update(setAgentKey)}/></Field></div><Field label="本次目标描述"><textarea value={goal} onChange={update(setGoal)} placeholder="选择模板后生成目标描述"/></Field><div className="section-label">执行阶段</div><div className="stages">{definition.steps.map((step:AnyRecord,index:number)=><div className="stage" key={step.title}><div className="stage-no">{String(index+1).padStart(2,"0")}</div><div><div className="stage-title">{step.title}</div><div className="stage-purpose">{step.purpose}</div><span className="stage-safety">{step.allowedPaths?.length?`白名单：${step.allowedPaths.join("、")}`:"受控操作"}</span></div></div>)}</div><div className="policy-grid"><Policy title="时间预算" value={`${definition.budget.maxDurationMinutes} 分钟`}/><Policy title="调用预算" value={`${definition.budget.maxToolCalls} 次工具调用`}/><Policy title="允许路径" value={definition.safety.allowedPaths.join("、")||"不写入"} safe/><Policy title="保护分支" value={definition.safety.protectedBranches.join("、")} safe/></div><div className="section-label section-label-gap">不可绕过的闸门</div><div className="guardrails">{[...definition.safety.forbiddenActions,...definition.escalationRules].map((r:string)=><div className="guardrail" key={r}>{r}</div>)}</div><div className="action-bar"><button className="secondary" onClick={()=>action("save")} type="button">保存项目</button><button className="secondary" onClick={()=>action("validate")} type="button">验证完整策略</button><button className="primary" onClick={()=>action("plan")} type="button">预览执行计划</button><button className="primary" onClick={()=>action("dispatch")} type="button">派发 Loop</button></div></div></section>
  <section className="panel wide monitor"><div className="monitor-main"><div className="run-header"><div><div className="eyebrow">Live run monitor</div><div className="run-title">{runs[0]?`${runs[0].loopName} · ${statusLabel(runs[0].status)}`:"还没有运行"}</div></div><span className="run-status active"><i className="dot live"/>{status}</span></div><div className="metrics"><Metric value="—" label="Inbox events"/><Metric value="—" label="Tasks"/><Metric value="—" label="Artifacts"/></div><div className="section-label">运行事件</div><div className="timeline">{events.length?events.map(e=><div className="event" key={e.id}><strong>{e.eventType}</strong><span>{JSON.stringify(e.payloadJson)}</span></div>):<Empty>验证或派发之后，运行事件会按最新顺序出现在这里。</Empty>}</div><div className="identity">Agent cell identity · <code>{project||"project"} / {loopName||"loop"} / {agentKey||"agent"}</code></div></div><div className="monitor-side"><div className="side-title">Recent runs</div><div className="recent-runs">{runs.slice(0,6).map(run=><button className="recent-run" key={run.id} onClick={()=>notify("已恢复运行事件。")} type="button"><span><strong>{run.projectName} · {run.loopName}</strong><span>{run.agentCellId}</span></span><b className="recent-run-status">{statusLabel(run.status)}</b></button>)}</div><div className="side-title side-title-gap">Decision branches</div><div className="decision-list">{definition.decisionRules.map((r:AnyRecord)=><div className="decision" key={r.signal}><strong>{r.signal}</strong><span>{r.action}</span></div>)}</div><p className="footer-note">Loop 的每个分支都必须留下证据；无法安全判断时，停止并升级给人。</p></div></section></div>{toast&&<div className="toast show" role="status">{toast}</div>}</main></div>;
}
function Brand({kicker}:{kicker:string}){return <div className="brand"><div className="brand-mark" aria-hidden="true">↻</div><div><div className="brand-name">looptask</div><div className="brand-kicker">{kicker}</div></div></div>}
function PanelHead({title,label}:{title:string;label:string}){return <div className="panel-head"><h2>{title}</h2><span className="step-count">{label}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Policy({title,value,safe=false}:{title:string;value:string;safe?:boolean}){return <div className={`policy ${safe?"safe":"warning"}`}><strong>{title}</strong><b>{value}</b></div>}
function Metric({value,label}:{value:string;label:string}){return <div className="metric"><b>{value}</b><span>{label}</span></div>}
function Empty({children}:{children:React.ReactNode}){return <div className="empty">{children}</div>}
function splitList(value:string){return value.split(",").map(i=>i.trim()).filter(Boolean)}
function statusLabel(status:string){return ({queued:"排队中",running:"运行中",passed:"已通过",failed:"失败","needs-human":"待人工"} as Record<string,string>)[status]||status}